// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
//
// Typed unified-method wrappers. Each `<id>_typed` module owns a venue
// Core and exposes the typed surface. `crate::<module>::<id>::<Core>`
// inside the wrappers resolves via the re-export below (or, for the pro
// layer, via this crate's own `pro` module).

pub mod binance_typed;
pub mod binanceusdm_typed;
pub mod bitget_typed;
pub mod bybit_typed;
pub mod gate_typed;
pub mod hyperliquid_typed;
pub mod okx_typed;
