// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
//
// Every exchange Core the live/offline test harness can dispatch to.
// `registry.rs` and `live_dispatch.rs` walk these macros, so the lists
// follow whatever Cores exist rather than being maintained by hand.
//
// Generated by `build/generateRustWrappers.ts`.

#![allow(unused_imports)]

pub(crate) use ccxt::exchanges::{
    binance::BinanceCore,
    binanceusdm::BinanceusdmCore,
    bitget::BitgetCore,
    bybit::BybitCore,
    gate::GateCore,
    hyperliquid::HyperliquidCore,
    okx::OkxCore,
};

pub(crate) use ccxt::prediction::{
    kalshi::KalshiCore,
    limitless::LimitlessCore,
    myriad::MyriadCore,
    opinion::OpinionCore,
    polymarket::PolymarketCore,
};

pub(crate) use ccxt::prediction::binance::BinanceCore as PredBinanceCore;
pub(crate) use ccxt::prediction::hyperliquid::HyperliquidCore as PredHyperliquidCore;

pub(crate) use ccxt_pro::pro::{
    binance::BinanceCore as WsBinanceCore,
    binanceusdm::BinanceusdmCore as WsBinanceusdmCore,
    bitget::BitgetCore as WsBitgetCore,
    bybit::BybitCore as WsBybitCore,
    gate::GateCore as WsGateCore,
    hyperliquid::HyperliquidCore as WsHyperliquidCore,
    okx::OkxCore as WsOkxCore,
};

macro_rules! for_each_core {
    ($cb:ident) => {
        $cb!(binance, BinanceCore);
        $cb!(binanceusdm, BinanceusdmCore);
        $cb!(bitget, BitgetCore);
        $cb!(bybit, BybitCore);
        $cb!(gate, GateCore);
        $cb!(hyperliquid, HyperliquidCore);
        $cb!(kalshi, KalshiCore);
        $cb!(limitless, LimitlessCore);
        $cb!(myriad, MyriadCore);
        $cb!(okx, OkxCore);
        $cb!(opinion, OpinionCore);
        $cb!(polymarket, PolymarketCore);
    };
}
pub(crate) use for_each_core;

macro_rules! for_each_ws_core {
    ($cb:ident) => {
        $cb!(binance, WsBinanceCore);
        $cb!(binanceusdm, WsBinanceusdmCore);
        $cb!(bitget, WsBitgetCore);
        $cb!(bybit, WsBybitCore);
        $cb!(gate, WsGateCore);
        $cb!(hyperliquid, WsHyperliquidCore);
        $cb!(okx, WsOkxCore);
    };
}
pub(crate) use for_each_ws_core;
